### ISSUE TITLE
Purpur 1.19.2 (1835)

### ISSUE THREAD

**Issue by hasankayra04** [pop4959/Stress#11] opened 2022-11-24 06:06 UTC
When i run the server, i do get the error below:
`[09:01:36 ERROR]: Could not pass event ServerTickEndEvent to Stress v1.0.3
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
        at java.util.LinkedList.get(LinkedList.java:480) ~[?:?]
        at org.popcraft.stress.tps.TickInterval.findNewMaxTick(TickInterval.java:238) ~[?:?]
        at org.popcraft.stress.tps.TickInterval.addTick(TickInterval.java:67) ~[?:?]
        at org.popcraft.stress.tps.TickProfiler.update(TickProfiler.java:38) ~[?:?]
        at org.popcraft.stress.tps.ServerTickEndEventTickProfiler.onServerTickEnd(ServerTickEndEventTickProfiler.java:19) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor44.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1835]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1835]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by pop4959** [comment] 2022-11-27 03:35
Tested on 1852 and not seeing this issue. Can you try updating?

**Comment by pop4959** [comment] 2022-12-09 08:46
Closing due to not being able to reproduce. Please let me know if you still have this issue and can provide reproduction steps.

**Closed as completed by pop4959** 2022-12-09 08:46 UTC
Labels: invalid
